--Organizacion en esquemas
CREATE SCHEMA Paciente AUTHORIZATION dbo;
CREATE SCHEMA Medico AUTHORIZATION dbo;
CREATE SCHEMA Cita AUTHORIZATION dbo;
CREATE SCHEMA Tratamiento AUTHORIZATION dbo;
CREATE SCHEMA Catalogo AUTHORIZATION dbo;

ALTER SCHEMA Paciente TRANSFER dbo.PACIENTE;
ALTER SCHEMA Paciente TRANSFER dbo.PACIENTE_TELEFONO;
ALTER SCHEMA Paciente TRANSFER dbo.PACIENTE_EMAIL;

ALTER SCHEMA Medico TRANSFER dbo.MEDICO;
ALTER SCHEMA Medico TRANSFER dbo.MEDICO_TELEFONO;
ALTER SCHEMA Medico TRANSFER dbo.MEDICO_EMAIL;

ALTER SCHEMA Cita TRANSFER dbo.FACTURA_CITA;

ALTER SCHEMA Tratamiento TRANSFER dbo.DETALLE_TRATAMIENTO;
ALTER SCHEMA Tratamiento TRANSFER dbo.DETALLEXMEDICAMENTO;

ALTER SCHEMA Catalogo TRANSFER dbo.MEDICAMENTO;