CREATE DATABASE GestionHospitalaria;
GO
USE GestionHospitalaria;
GO

--CREANDO LAS TABLAS
CREATE TABLE PACIENTE (
    id_paciente INT IDENTITY(1,1) PRIMARY KEY,
    dui VARCHAR(10) NOT NULL UNIQUE,
    numero_seguro VARCHAR(20),
    nombre NVARCHAR(100) NOT NULL
);
GO
CREATE TABLE PACIENTE_EMAIL (
    id_paciente_email INT IDENTITY(1,1) PRIMARY KEY,
    id_paciente INT NOT NULL,
    email NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_PACIENTE_EMAIL_PACIENTE
    FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id_paciente)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE TABLE PACIENTE_TELEFONO (
    id_paciente_telefono INT IDENTITY(1,1) PRIMARY KEY,
    id_paciente INT NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    CONSTRAINT FK_PACIENTE_TELEFONO_PACIENTE
    FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id_paciente)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE TABLE MEDICO (
    id_medico INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(100) NOT NULL,
    especialidad NVARCHAR(100),
    dui VARCHAR(10) NOT NULL UNIQUE
);
GO
CREATE TABLE MEDICO_EMAIL (
    id_medico_email INT IDENTITY(1,1) PRIMARY KEY,
    id_medico INT NOT NULL,
    email NVARCHAR(100) NOT NULL,
    CONSTRAINT FK_MEDICO_EMAIL_MEDICO
    FOREIGN KEY (id_medico) REFERENCES MEDICO(id_medico)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE TABLE MEDICO_TELEFONO (
    id_medico_telefono INT IDENTITY(1,1) PRIMARY KEY,
    id_medico INT NOT NULL,
    telefono VARCHAR(15) NOT NULL,
    CONSTRAINT FK_MEDICO_TELEFONO_MEDICO
    FOREIGN KEY (id_medico) REFERENCES MEDICO(id_medico)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE TABLE FACTURA_CITA (
    id_factura_cita INT IDENTITY(1,1) PRIMARY KEY,
    id_paciente INT NOT NULL,
    id_medico INT NOT NULL,
    fecha_cita DATE NOT NULL,
    numero_factura VARCHAR(20) UNIQUE,
    total_costo DECIMAL(10,2),
    CONSTRAINT FK_FACTURA_PACIENTE 
    FOREIGN KEY (id_paciente) REFERENCES PACIENTE(id_paciente)ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_FACTURA_MEDICO 
    FOREIGN KEY (id_medico) REFERENCES MEDICO(id_medico)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
CREATE TABLE DETALLE_TRATAMIENTO (
    id_tratamiento INT IDENTITY(1,1) PRIMARY KEY,
    id_factura_cita INT NOT NULL,
    nombre NVARCHAR(100) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    descripcion NVARCHAR(255),
    CONSTRAINT FK_TRATAMIENTO_FACTURA
        FOREIGN KEY (id_factura_cita) REFERENCES FACTURA_CITA(id_factura_cita)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
GO
CREATE TABLE MEDICAMENTO (
    id_medicamento INT IDENTITY(1,1) PRIMARY KEY,
    nombre NVARCHAR(100) NOT NULL,
    marca NVARCHAR(100),
    precio DECIMAL(10,2)
);
GO
CREATE TABLE DETALLEXMEDICAMENTO (
    id_tratamientoxequipo INT IDENTITY(1,1) PRIMARY KEY,
    id_tratamiento INT NOT NULL,
    id_medicamento INT NOT NULL,
    cantidad INT NOT NULL,
    CONSTRAINT FK_DETALLE_MEDICAMENTO_TRATAMIENTO
    FOREIGN KEY (id_tratamiento) REFERENCES DETALLE_TRATAMIENTO(id_tratamiento)ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_DETALLE_MEDICAMENTO_MEDICAMENTO
    FOREIGN KEY (id_medicamento) REFERENCES MEDICAMENTO(id_medicamento)ON DELETE CASCADE ON UPDATE CASCADE
);
GO
